const actionTypes = {
    SET_MOVIES: 'SET_MOVIES',
    SET_LOGIN_DIALOG_OPENED: 'SET_LOGIN_DIALOG_OPENED',
    SET_ACTIVE_REQUESTS: 'SET_ACTIVE_REQUESTS',
    ADD_ACTIVE_REQUEST: 'ADD_ACTIVE_REQUEST',
    REMOVE_ACTIVE_REQUEST: 'REMOVE_ACTIVE_REQUEST',
}
export default actionTypes;